apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-data
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/fasfood-fiap-postech/database/data/