apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres-data
  labels:
    name: pvc-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: postgres-data