apiVersion: v1
kind: Secret
metadata:
  name: postgres-data-secret-prod
type: Opaque
data:
  DB_HOSTNAME: {{DB_HOSTNAME_KEY}}
  DB_PORT: {{DB_PORT_KEY}}
  DB_USERNAME: {{DB_USERNAME_KEY}}
  DB_PASSWORD: {{DB_PASSWORD_KEY}}
---
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-data-secret-prod
type: Opaque
data:
  API_GATEWAY_URL: {{API_GATEWAY_URL}}