apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-fiap-postech-prod
  labels:
    app: fastfood-fiap-postech-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastfood-fiap-postech-prod
  template:
    metadata:
      labels:
        app: fastfood-fiap-postech-prod
    spec:
      containers:
      - name: fastfood-fiap-postech-prod
        image: guibaarros/fastfood-fiap-postech:{{VERSION}}
        env:
          - name: DB_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: postgres-data-secret-prod
                key: DB_HOSTNAME
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres-data-secret-prod
                key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-data-secret-prod
                key: DB_PASSWORD
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: postgres-data-secret-prod
                key: DB_PORT
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8085
          periodSeconds: 60
          failureThreshold: 3
          initialDelaySeconds: 60
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8085
          periodSeconds: 60
          failureThreshold: 3
          initialDelaySeconds: 60
        resources:
          limits:
            memory: "512Mi"
            cpu: "300m"
        ports:
        - containerPort: 8085
