apiVersion: v1
kind: Service
metadata:
  name: svc-fastfood-fiap-postech-load-balancer-dev
spec:
  selector:
    app: fastfood-fiap-postech-dev
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
