name: "Integração Contínua"
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  testes-unitarios:
    name: "Testes unitários"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Configura Java 17"
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: "Permissiona a execução do ./gradlew"
        run: chmod +x ./gradlew
      - name: "Executa os testes"
        run: ./gradlew test --info

  analise-estatica:
    name: "Análise Estática - Sonar Cloud"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Configura Java 17"
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: "Adiciona cache aos pacotes do Sonar"
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: "Adiciona cache aos pacotes do Gradle"
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: "Permissiona a execução do ./gradlew"
        run: chmod +x ./gradlew
      - name: "Executa o build e analisa o código"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar -x test --info

  build:
    name: "Executa o build"
    runs-on: ubuntu-latest
    needs: [testes-unitarios, analise-estatica]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Configura Java 17"
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: "Permissiona a execução do ./gradlew"
        run: chmod +x ./gradlew
      - name: "Executa o build"
        run: ./gradlew build --info
